stages:
  - build

variables:
  BUILD_DIR: build

build:
  stage: build
  tags:
    - windows
  script:
    - echo "Checking out code"
    - git clone $CI_REPOSITORY_URL
    - echo "Checking CMake version"
    - cmake --version
    - echo "Setting up MSVC environment"
    - call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools/VsDevCmd.bat"
    - echo "Generating CMake project"
    - cmake -D CMAKE_BUILD_TYPE=RelWithDebInfo -D OPTIMIZE=YES -S . -B $BUILD_DIR -G Ninja
    - echo "Building 64bit release DLL"
    - cmake --build $BUILD_DIR --config RelWithDebInfo --target YimMenu --
    - echo "Checking if DLL got built"
    - if not exist $BUILD_DIR/YimMenu.dll exit 1
    - echo "Renaming DLL"
    - del YimMenu-dev-*.dll
    - del YimMenu-dev-*.pdb
    - rename $BUILD_DIR/YimMenu.dll YimMenu-dev-%CI_COMMIT_SHA%.dll
    - rename $BUILD_DIR/YimMenu.pdb YimMenu.pdb
  artifacts:
    paths:
      - $BUILD_DIR/YimMenu-dev-*.dll
      - $BUILD_DIR/YimMenu.pdb
