stages:
  - check
  - build
  - release

variables:
  GIT_DEPTH: 1
  MSVC_DEV_CMD_VERSION: "v1"

check_recent_commit:
  stage: check
  image: ubuntu:latest
  script:
    - git fetch --unshallow
    - if [ -z "$(git rev-list --since="24 hours ago" --all)" ]; then echo "No recent commits"; exit 0; fi
  artifacts:
    reports:
      dotenv: should_run.env
  only:
    - schedules

build_nightly:
  stage: build
  tags:
    - windows
  needs:
    - check_recent_commit
  script:
    - cmake --version
    - cmake -D CMAKE_BUILD_TYPE=RelWithDebInfo -D OPTIMIZE=YES -S . -B build -G Ninja
    - cmake --build ./build --config RelWithDebInfo --target YimMenu --
  artifacts:
    paths:
      - build/YimMenu.dll
      - build/YimMenu.pdb
    when: on_success
  only:
    - schedules

recreate_release:
  stage: release
  image: ubuntu:latest
  needs:
    - build_nightly
  script:
    - |
      if [ -f should_run.env ] && [ "$(grep -oP '(?<=should_run=).*' should_run.env)" == "false" ]; then
        echo "No recent commits, skipping release"; exit 0;
      fi
    - curl -LO https://releases.hashicorp.com/jq/1.6/jq-linux64 && chmod +x jq-linux64 && mv jq-linux64 /usr/bin/jq
    - |
      existing_release_id=$(curl --header "PRIVATE-TOKEN: ${CI_API_TOKEN}" "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/releases" | jq '.[] | select(.tag_name == "nightly") | .id')
      if [ -n "$existing_release_id" ]; then
        curl --request DELETE --header "PRIVATE-TOKEN: ${CI_API_TOKEN}" "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/releases/${existing_release_id}"
      fi
    - sha256sum build/YimMenu.dll > sha256.checksum
    - |
      curl --request POST --header "PRIVATE-TOKEN: ${CI_API_TOKEN}" \
        --form "name=Nightly Build" \
        --form "tag_name=nightly" \
        --form "description=Nightly build for ${CI_COMMIT_SHA}" \
        --form "assets[links][][name]=YimMenu.dll" \
        --form "assets[links][][url]=${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/file/build/YimMenu.dll" \
        "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/releases"
  only:
    - schedules
